# wrangler.toml
name = "my-analytics-app"
main = "my-analytics-app/.open-next/worker.js"
compatibility_date = "2025-10-22"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "my-analytics-app/.open-next/assets"
